name: Generate Snake Animation

on:
  # This section is now correctly indented
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    # This permission is required for the Action to write files to your repository
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      # Checks out your repository so the Action can write to it
      - uses: actions/checkout@v3

      # Generates the snake files
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          
          # This saves the files to an 'output' folder in your main branch
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark

      # Commits the generated files to your repository
      - name: Commit and push snake animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: generate contribution snake"
          file_pattern: output/*.svg
          branch: main # or master, depending on your default branch name
